# Generated by Django 4.1 on 2026-05-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bin_id", models.CharField(max_length=100)),
                ("distance_cm", models.FloatField()),
                ("fill_percentage", models.IntegerField()),
                ("temperature_c", models.FloatField()),
                ("humidity", models.FloatField()),
                ("flame_detected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
